import Head from "next/head";
import { useEffect, useState } from "react";
import { useRouter } from "next/router";

const ProductDetail = () => {
    const router = useRouter();
    const { productId } = router.query;

    const [product, setProduct] = useState(null);

    useEffect(() => {
      const getProduct = async () => {
        try {
        const response = await fetch(`/api/products/${productId}`)
          if (response.ok) {
             const data = await response.json()
             setProduct(data);
            } else {
              throw new Error(
                `Fetch fehlgeschlagen mit Status: ${response.status}`
              );
           } 
           } catch (error) {
            console.log(error);
            alert(error.message);
           }
         };
          getProduct();
         }, []);

    return (
    <>
      <Head>
        <title>Product Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>Product details for product: {productId}</div>
      {product ? (
      <>
      <p>Id: {product.id}</p>
      <p>Name: {product.name}</p>
      <p>Category: {product.category}</p>
    </>
  ) : (
    <p>Loading...</p>
  )}
  </>
    );
};

export default ProductDetail;