import Head from 'next/head'
import Image from 'next/image'
import Link from "next/link";
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>My first Next.js App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles["main"]}>
        <Link href="/">Home</Link>
        <Link href="/products">Products</Link>
        <h1>
          Welcome to my first Next.js app!
        </h1>
        <h2>Hello World!</h2>
      </main>
    </div>
  )
}
